# Generated by Django 4.1.7 on 2023-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=2)),
                ('HP', models.IntegerField()),
                ('Helmet', models.CharField(max_length=50)),
                ('Torso', models.CharField(max_length=50)),
                ('Gloves', models.CharField(max_length=50)),
                ('Boots', models.CharField(max_length=50)),
                ('LeftHand', models.CharField(max_length=50)),
                ('RightHand', models.CharField(max_length=50)),
                ('Side', models.CharField(max_length=50)),
                ('INT', models.IntegerField()),
                ('SIŁ', models.IntegerField()),
                ('ZRE', models.IntegerField()),
                ('CHAR', models.IntegerField()),
                ('CEL', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Eq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('found', models.BooleanField()),
                ('stats', models.CharField(max_length=50)),
                ('skill', models.TextField()),
                ('weight', models.DecimalField(decimal_places=1, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('INT', models.IntegerField()),
                ('SIŁ', models.IntegerField()),
                ('ZRE', models.IntegerField()),
                ('CHAR', models.IntegerField()),
                ('CEL', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
                ('character', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
    ]
