# Generated by Django 4.1.7 on 2023-03-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0006_skills_decs_category_skills_decs_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='points_left',
            field=models.IntegerField(null=True),
        ),
    ]
