# Generated by Django 4.1.7 on 2023-03-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0012_alter_skills_decs_level2_alter_skills_decs_level3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='cost',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
