# Generated by Django 4.1.7 on 2023-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0017_items_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='skill',
            field=models.TextField(blank=True),
        ),
    ]
