# Generated by Django 4.1.7 on 2023-04-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0019_items_highlighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=5)),
                ('statPlus', models.CharField(max_length=255)),
                ('statMinus', models.CharField(max_length=255)),
                ('Skills', models.CharField(max_length=255)),
                ('points_limit', models.IntegerField()),
            ],
        ),
    ]
