# Generated by Django 4.1.7 on 2023-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0020_races'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='Skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='races',
            name='statMinus',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='races',
            name='statPlus',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
