# Generated by Django 4.1.7 on 2023-04-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0024_alter_skills_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mods',
            name='CEL',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='CHAR',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='INT',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='SIŁ',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='ZRE',
        ),
        migrations.AddField(
            model_name='mods',
            name='field',
            field=models.CharField(default='INT', max_length=10),
        ),
        migrations.AddField(
            model_name='mods',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mods',
            name='character',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mods',
            name='owner',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
