# Generated by Django 4.1.7 on 2023-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0025_remove_mods_cel_remove_mods_char_remove_mods_int_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mods',
            old_name='value',
            new_name='CEL',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='field',
        ),
        migrations.AddField(
            model_name='mods',
            name='CHAR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mods',
            name='INT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mods',
            name='SIŁ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mods',
            name='ZRE',
            field=models.IntegerField(default=0),
        ),
    ]
