# Generated by Django 4.1.7 on 2023-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0027_remove_items_highlighted_alter_items_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mods',
            old_name='CEL',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='CHAR',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='INT',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='SIŁ',
        ),
        migrations.RemoveField(
            model_name='mods',
            name='ZRE',
        ),
        migrations.AddField(
            model_name='mods',
            name='field',
            field=models.CharField(default='INT', max_length=10),
        ),
    ]
