# Generated by Django 4.1.7 on 2023-04-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0031_character_weaponbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='preferencedWeapons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='unlikedWeapons',
            field=models.TextField(blank=True),
        ),
    ]
