# Generated by Django 4.1.7 on 2023-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0032_character_preferencedweapons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='points_limit',
            field=models.IntegerField(null=True),
        ),
    ]
