# Generated by Django 4.1.7 on 2023-05-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0035_rename_preferencedweapons_character_preferredweapons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effects_Decs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('attack', 'attack'), ('parry', 'parry'), ('attack&parry', 'attack&parry'), ('all', 'all'), ('other', 'other'), ('dodge', 'dodge'), ('agility', 'agility'), ('sneaking', 'sneaking'), ('resistance', 'resistance'), ('regeneration', 'regeneration'), ('armor', 'armor'), ('resting', 'resting'), ('poison', 'poison')], max_length=150)),
                ('desc', models.TextField()),
                ('bonus', models.IntegerField(null=True)),
            ],
        ),
    ]
