# Generated by Django 4.1.7 on 2023-05-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0038_alter_effects_decs_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='points_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='preferredWeapons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='races',
            name='unlikedWeapons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='races',
            name='weaponBonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='weaponsBonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='weaponsPreffered',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='weaponsUnliked',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
