# Generated by Django 4.1.7 on 2023-05-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0039_races_points_left_races_preferredweapons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='races',
            name='preferredWeapons',
        ),
        migrations.RemoveField(
            model_name='races',
            name='unlikedWeapons',
        ),
        migrations.RemoveField(
            model_name='races',
            name='weaponBonus',
        ),
    ]
