# Generated by Django 4.1.7 on 2023-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0041_remove_races_points_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='weaponsPreffered',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='weaponsUnliked',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
