# Generated by Django 4.1.7 on 2023-05-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0044_items_ap_items_altattack_items_block_items_dicebonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='stats',
        ),
    ]
