# Generated by Django 4.1.7 on 2023-05-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0048_items_neededaccuraccy'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
