# Generated by Django 4.1.7 on 2023-05-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0049_items_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='neededAccuraccy',
            field=models.IntegerField(default=0),
        ),
    ]
