# Generated by Django 4.1.7 on 2023-05-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0050_alter_items_neededaccuraccy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='currentDurability',
        ),
    ]
