# Generated by Django 4.1.7 on 2023-05-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0051_remove_items_currentdurability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='neededAccuraccy',
            field=models.IntegerField(default=5),
        ),
    ]
