# Generated by Django 4.1.7 on 2023-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0053_remove_effects_category_remove_effects_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='effects_decs',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
