# Generated by Django 4.1.7 on 2023-03-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0003_character_eq_items_mods_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
