# Generated by Django 4.1.7 on 2023-03-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0005_skills_decs'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
