# Generated by Django 4.1.7 on 2023-03-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0007_character_points_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='fullHP',
            field=models.IntegerField(null=True),
        ),
    ]
