# Generated by Django 4.1.7 on 2023-03-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0008_character_fullhp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Boots',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='Gloves',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='Helmet',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='LeftHand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='RightHand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='Side',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='character',
            name='Torso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
