# Generated by Django 4.1.7 on 2023-03-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0009_alter_character_boots_alter_character_gloves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_decs',
            name='cost',
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='level1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='level2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='level3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='level4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
