# Generated by Django 4.1.7 on 2023-03-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0010_remove_skills_decs_cost_skills_decs_level1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='need1_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need1_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need2_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need2_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need3_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need3_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need4_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='need4_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
