# Generated by Django 4.1.7 on 2023-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0011_skills_decs_need1_1_skills_decs_need1_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills_decs',
            name='level2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='level3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='level4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need1_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need1_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need2_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need2_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need3_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need3_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need4_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='need4_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
