# Generated by Django 4.1.7 on 2023-03-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0014_alter_skills_decs_level1_alter_skills_decs_level2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='useAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
