# Generated by Django 4.1.7 on 2023-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0015_skills_decs_useamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
