# Generated by Django 4.1.7 on 2023-04-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0018_alter_items_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='highlighted',
            field=models.TextField(null=True),
        ),
    ]
