# Generated by Django 4.1.7 on 2023-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0026_rename_value_mods_cel_remove_mods_field_mods_char_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='highlighted',
        ),
        migrations.AlterField(
            model_name='items',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='stats',
            field=models.CharField(default='1K+0, 0AP', max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=50),
        ),
    ]
