# Generated by Django 4.1.7 on 2023-04-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0028_rename_cel_mods_value_remove_mods_char_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=150)),
                ('character', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
