# Generated by Django 4.1.7 on 2023-04-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0030_effects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='weaponBonus',
            field=models.IntegerField(null=True),
        ),
    ]
