# Generated by Django 4.1.7 on 2023-04-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0033_alter_races_points_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='dualHanded',
            field=models.BooleanField(default=False),
        ),
    ]
