# Generated by Django 4.1.7 on 2023-04-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0034_items_dualhanded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='preferencedWeapons',
            new_name='preferredWeapons',
        ),
    ]
