# Generated by Django 4.1.7 on 2023-05-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0036_effects_decs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effects_decs',
            name='category',
            field=models.CharField(choices=[('attack', 'attack'), ('parry', 'parry'), ('attack&parry', 'attack&parry'), ('all', 'all'), ('other', 'other'), ('dodge', 'dodge'), ('agility', 'agility'), ('sneaking', 'sneaking'), ('resistance', 'resistance'), ('regeneration', 'regeneration'), ('armor', 'armor'), ('resting', 'resting'), ('poison', 'poison'), ('cel', 'cel')], max_length=150),
        ),
    ]
