# Generated by Django 4.1.7 on 2023-05-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0037_alter_effects_decs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effects_decs',
            name='bonus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
