# Generated by Django 4.1.7 on 2023-05-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0042_alter_races_weaponspreffered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='rarity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
