# Generated by Django 4.1.7 on 2023-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0043_items_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='AP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='altAttack',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='items',
            name='block',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='diceBonus',
            field=models.IntegerField(default=0),
        ),
    ]
