# Generated by Django 4.1.7 on 2023-05-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0045_remove_items_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='currentDurability',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='items',
            name='maxDurability',
            field=models.IntegerField(default=50),
        ),
    ]
