# Generated by Django 4.1.7 on 2023-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0046_items_currentdurability_items_maxdurability'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='armor',
            field=models.IntegerField(default=0),
        ),
    ]
