# Generated by Django 4.1.7 on 2023-05-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0052_alter_items_neededaccuraccy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effects',
            name='category',
        ),
        migrations.RemoveField(
            model_name='effects',
            name='desc',
        ),
    ]
