# Generated by Django 4.1.7 on 2023-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0056_alter_character_preferredweapons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=80)),
                ('character', models.CharField(max_length=150)),
                ('item_name', models.CharField(max_length=150)),
                ('durability', models.IntegerField(default=50)),
            ],
        ),
        migrations.AlterField(
            model_name='effects_decs',
            name='category',
            field=models.CharField(choices=[('attack', 'attack'), ('parry', 'parry'), ('attack&parry', 'attack&parry'), ('dodge&parry', 'dodge&parry'), ('all', 'all'), ('other', 'other'), ('dodge', 'dodge'), ('agility', 'agility'), ('sneaking', 'sneaking'), ('resistance', 'resistance'), ('regeneration', 'regeneration'), ('armor', 'armor'), ('resting', 'resting'), ('poison', 'poison'), ('cel', 'cel')], max_length=150),
        ),
    ]
