# Generated by Django 4.1.7 on 2023-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0057_charitems_alter_effects_decs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitems',
            name='hand',
            field=models.CharField(default='Left', max_length=10),
        ),
    ]
