# Generated by Django 4.1.7 on 2023-06-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0058_charitems_hand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charitems',
            old_name='item_name',
            new_name='name',
        ),
    ]
