# Generated by Django 4.2.1 on 2023-06-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0060_remove_character_lefthand_remove_character_righthand'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='items',
            name='neededAccuraccy',
            field=models.IntegerField(default=6),
        ),
    ]
