# Generated by Django 4.2.1 on 2023-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0062_charitems_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitems',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
