# Generated by Django 4.2.1 on 2023-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0063_alter_charitems_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitems',
            name='hand',
            field=models.CharField(blank=True, default='Left', max_length=10, null=True),
        ),
    ]
