# Generated by Django 4.1.7 on 2023-06-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0064_alter_charitems_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='skillEffects',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='skillStats',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
