# Generated by Django 4.2.1 on 2023-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0066_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='character',
        ),
        migrations.AddField(
            model_name='requests',
            name='char_id',
            field=models.IntegerField(null=True),
        ),
    ]
