# Generated by Django 4.1.7 on 2023-07-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0068_remove_requests_filter_id_requests_object1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='objects_model',
            field=models.CharField(default='Items', max_length=150),
        ),
    ]
