# Generated by Django 4.2.1 on 2023-07-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0069_requests_objects_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq',
            name='durability',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='eq',
            name='character',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='eq',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='eq',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
