# Generated by Django 4.2.1 on 2023-07-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0070_eq_durability_alter_eq_character_alter_eq_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq',
            name='type',
            field=models.CharField(default='Other', max_length=80),
        ),
    ]
