# Generated by Django 4.2.1 on 2023-07-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0073_character_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=150)),
                ('items', models.TextField()),
                ('magic_school', models.BooleanField(default=False)),
                ('champion_school_type', models.CharField(max_length=150)),
                ('visiting', models.BooleanField(default=False)),
            ],
        ),
    ]
