# Generated by Django 4.2.1 on 2023-07-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0075_eq_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='chosen_class',
            field=models.CharField(default='', max_length=80),
        ),
    ]
