# Generated by Django 4.2.1 on 2023-08-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0076_character_chosen_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='chosen_class',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
