# Generated by Django 4.1.7 on 2023-08-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0077_alter_character_chosen_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='useslvl1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='useslvl2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='useslvl3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='useslvl4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
