# Generated by Django 4.1.7 on 2023-09-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0080_character_extra_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
