# Generated by Django 4.2.1 on 2023-09-29 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0081_character_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='model_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
