# Generated by Django 4.2.1 on 2023-09-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0082_character_model_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='model_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
