# Generated by Django 4.2.1 on 2024-12-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0085_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='hp_mod',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='classes',
            name='mods',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
