# Generated by Django 4.2.1 on 2024-12-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0086_classes_hp_mod_classes_mods'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='allowed_weapons',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='classes',
            name='forbidden_skills',
            field=models.TextField(blank=True),
        ),
    ]
