# Generated by Django 4.2.1 on 2024-12-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0087_classes_allowed_weapons_classes_forbidden_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='important',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
