# Generated by Django 4.2.1 on 2025-01-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0088_classes_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
