# Generated by Django 4.2.1 on 2025-12-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0089_classes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
