# Generated by Django 4.2.1 on 2025-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0090_items_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
