# Generated by Django 4.2.1 on 2025-12-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0091_requests_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='effectsAfterPen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='effectsAlways',
            field=models.TextField(blank=True, null=True),
        ),
    ]
