# Generated by Django 4.2.1 on 2026-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0092_items_effectsafterpen_items_effectsalways'),
    ]

    operations = [
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_stopped', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mutations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('effect', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='diceBonus',
        ),
        migrations.AddField(
            model_name='character',
            name='alcohol',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='barrier',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='character',
            name='city_bargains',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='food',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='mutation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='water',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='charitems',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='charitems',
            name='effectsafterpen',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='charitems',
            name='effectsall',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='charitems',
            name='on_use',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='charitems',
            name='use_cost',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='dmgDice',
            field=models.CharField(default='1K10', max_length=50),
        ),
        migrations.AddField(
            model_name='items',
            name='dmgModifier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='items',
            name='dmg_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='on_use',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='use_cost',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='restrictions',
            field=models.CharField(default='all', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='coins',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
