# Generated by Django 4.2.1 on 2026-02-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0093_gm_mutations_remove_items_dicebonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills_decs',
            name='restrictions',
            field=models.CharField(default='Uniwersalne', max_length=255),
        ),
    ]
