# Generated by Django 4.2.1 on 2026-03-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0094_alter_skills_decs_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='hp',
            field=models.IntegerField(default=16),
        ),
    ]
