# Generated by Django 4.2.1 on 2026-03-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0095_races_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills_decs',
            name='need1_1',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need1_2',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need2_1',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need2_2',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need3_1',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need3_2',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need4_1',
        ),
        migrations.RemoveField(
            model_name='skills_decs',
            name='need4_2',
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='reqs1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='reqs2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='reqs3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='reqs4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
