# Generated by Django 4.2.1 on 2026-03-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0096_remove_skills_decs_need1_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='SPO',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
