# Generated by Django 4.2.1 on 2026-03-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0097_character_spo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='SPO',
            field=models.IntegerField(default=0),
        ),
    ]
