# Generated by Django 4.2.1 on 2026-03-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0098_alter_character_spo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='mutation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
