# Generated by Django 4.2.1 on 2026-03-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0099_alter_character_mutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='use_cost',
            field=models.CharField(default='full', max_length=255),
        ),
    ]
