# Generated by Django 4.2.1 on 2026-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0100_skills_decs_use_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='actionLeft',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='skills_decs',
            name='use_cost',
            field=models.FloatField(default=1.0),
        ),
    ]
