# Generated by Django 4.2.1 on 2026-04-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0101_character_actionleft_alter_skills_decs_use_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitems',
            name='reloaded',
            field=models.BooleanField(default=True),
        ),
    ]
