# Generated by Django 4.2.1 on 2026-04-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0102_charitems_reloaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='effects',
            name='bonus',
        ),
        migrations.AddField(
            model_name='effects',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eq',
            name='reloaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='effects_decs',
            name='category',
            field=models.CharField(max_length=150),
        ),
    ]
