# Generated by Django 4.2.1 on 2026-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0103_remove_effects_bonus_effects_desc_eq_reloaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='preferredWeapons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='unlikedWeapons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
