# Generated by Django 4.2.1 on 2026-04-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0104_alter_character_preferredweapons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='category',
            field=models.CharField(default='Informacyjne', max_length=15),
        ),
    ]
