# Generated by Django 4.2.1 on 2026-04-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0105_effects_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='use_info',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
