# Generated by Django 4.2.1 on 2026-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0106_items_use_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inFight',
            field=models.BooleanField(default=False),
        ),
    ]
