# Generated by Django 4.2.1 on 2026-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0107_character_infight'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='maxBarrier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='barrier',
            field=models.IntegerField(default=0),
        ),
    ]
