# Generated by Django 4.2.1 on 2026-04-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0108_character_counter_character_maxbarrier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='counter2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='counterName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='counterName2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
