# Generated by Django 4.2.1 on 2026-04-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0109_character_counter2_character_countername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='anonimity',
            field=models.IntegerField(default=0),
        ),
    ]
