# Generated by Django 4.2.1 on 2026-04-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0110_character_anonimity'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='requiredCel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
