# Generated by Django 4.2.1 on 2026-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0111_skills_decs_range_skills_decs_requiredcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills_decs',
            name='ap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skills_decs',
            name='dice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
