# Generated by Django 4.2.1 on 2026-05-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0112_skills_decs_ap_skills_decs_dice'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='armor_weight',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='dmg_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='on_use',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='use_cost',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='use_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
