# Generated by Django 4.2.1 on 2026-05-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0113_items_armor_weight_alter_items_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='grantedSkills',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='use_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
