# Generated by Django 4.2.1 on 2026-05-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0114_items_grantedskills_items_use_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='added_lvl_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skills',
            name='source',
            field=models.CharField(default='natural', max_length=255),
        ),
    ]
