# Generated by Django 4.2.1 on 2026-05-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0115_skills_added_lvl_info_skills_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='mobilityChange',
            field=models.IntegerField(default=0),
        ),
    ]
