# Generated by Django 4.2.1 on 2026-05-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0116_races_mobilitychange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='unlikedWeapons',
        ),
        migrations.RemoveField(
            model_name='races',
            name='weaponsUnliked',
        ),
    ]
