# Generated by Django 4.2.1 on 2026-06-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0117_remove_character_unlikedweapons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
