# Generated by Django 4.2.1 on 2026-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0118_mods_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='works_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
