# Generated by Django 4.2.1 on 2026-06-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0119_effects_works_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
