# Generated by Django 4.2.1 on 2026-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0120_effects_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ammo_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
