# Generated by Django 4.2.1 on 2026-06-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0121_items_ammo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='extra_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='mobility',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
