# Generated by Django 4.2.1 on 2026-07-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0125_items_unobtainable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('chaapter', models.CharField(max_length=255, null=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
