# Generated by Django 4.2.1 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0126_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='chaapter',
            new_name='chapter',
        ),
        migrations.AlterField(
            model_name='images',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
