# Generated by Django 4.2.1 on 2026-07-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0127_rename_chaapter_images_chapter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.CharField(default='Tzeentch', max_length=255)),
            ],
        ),
    ]
