# Generated by Django 4.2.1 on 2026-07-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0128_gamesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
