# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0131_character_advantagebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='mods',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
