# Generated by Django 4.2.1 on 2026-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DunnoRPG', '0132_mods_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='dmgModifier',
            field=models.FloatField(default=1),
        ),
    ]
